import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/public/header/Header";
import Footer from "@/components/public/header/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>)
{
    return (
        <html lang="kr">
            <head />
            <body className={ inter.className }>
                <Header />
                { children }
                <Footer />
            </body>
        </html>
    );
}
